apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  users.anonymous.enabled: "true"
  repositories: |
    - url: https://github.com/espinm2/miniverse.git
      insecure: true
      insecureIgnoreHostKey: true
      type: git
    - url: https://github.com/nats-io/k8s.git
      insecure: true
      insecureIgnoreHostKey: true
      type: git
    - url: https://dapr.github.io/helm-charts/
      insecure: true
      insecureIgnoreHostKey: true
      type: helm
    - url: https://istio-release.storage.googleapis.com/charts
      insecure: true
      insecureIgnoreHostKey: true
      type: helm
