apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  url: http://localhost:8080/argocd/
  repositories: |
    - url: https://github.com/espinm2/miniverse.git
      insecure: true
      insecureIgnoreHostKey: true
      type: git
    - url: https://github.com/helm/charts.git
      insecure: true
      insecureIgnoreHostKey: true
      type: git
